"""Turn Nsight Compute reports into the Markdown table the README quotes.

    python profiling/summarize_ncu.py results/ncu --out results/NCU.md

A screenshot of the Nsight Compute GUI is not reproducible and not diffable.
This pulls the same metrics out of the `.ncu-rep` files as text, so every
profiler claim in the README can be regenerated by rerunning one command. The
`.ncu-rep` files are kept alongside for opening in the GUI.

Metrics chosen to answer the three questions the README actually asks:
  is it memory bound      -> DRAM throughput % of peak, compute throughput %
  are the loads coalesced -> sectors per global load request. A warp issuing
                             128-bit (16 B) loads touches 32 x 16 B = 512 B =
                             16 x 32 B sectors, so 16 is the ideal for this
                             kernel and 32 would mean every lane pulled its own
                             sector (fully scattered).
  is the GPU full         -> grid size vs SM count, achieved occupancy
"""

from __future__ import annotations

import argparse
import csv
import io
import pathlib
import shutil
import subprocess
import sys

# metric name -> (short column label, unit hint)
WANTED = {
    "gpu__time_duration.sum": ("time", "us"),
    "gpu__dram_throughput.avg.pct_of_peak_sustained_elapsed": ("DRAM %peak", "%"),
    "sm__throughput.avg.pct_of_peak_sustained_elapsed": ("SM %peak", "%"),
    "dram__bytes_read.sum.per_second": ("DRAM read", "GB/s"),
    "sm__warps_active.avg.pct_of_peak_sustained_active": ("occupancy", "%"),
    "l1tex__average_t_sectors_per_request_pipe_lsu_mem_global_op_ld.ratio":
        ("sectors/req", ""),
    "launch__grid_size": ("grid", ""),
    "launch__block_size": ("block", ""),
    "launch__registers_per_thread": ("regs", ""),
    "sm__pipe_tensor_cycles_active.avg.pct_of_peak_sustained_active":
        ("tensor %", "%"),
}


def find_ncu() -> str:
    """Resolve ncu.exe, never the .bat wrapper.

    The wrapper forwards its arguments through cmd.exe, which splits a
    kernel-name regex on its `|` and then tries to run the right-hand side as a
    command. Everything here goes straight to the executable.
    """
    for p in sorted(pathlib.Path(r"C:\Program Files\NVIDIA Corporation").glob(
            "Nsight Compute*/target/*/ncu.exe")):
        return str(p)
    exe = shutil.which("ncu")
    if exe and exe.lower().endswith(".exe"):
        return exe
    raise SystemExit("ncu.exe not found on PATH or under Program Files")


def read_report(ncu: str, rep: pathlib.Path) -> list[dict]:
    """Return one dict of metrics per profiled kernel launch."""
    res = subprocess.run(
        [ncu, "--import", str(rep), "--page", "raw", "--csv"],
        capture_output=True, text=True,
    )
    if res.returncode != 0 or not res.stdout.strip():
        return []
    # ncu prints banner lines before the CSV header; skip to the header row.
    lines = res.stdout.splitlines()
    start = next((i for i, l in enumerate(lines) if l.startswith('"ID"')), 0)
    rows = list(csv.DictReader(io.StringIO("\n".join(lines[start:]))))
    return rows


def summarize(rows: list[dict]) -> dict[str, dict[str, float]]:
    """Average each wanted metric per kernel name."""
    by_kernel: dict[str, list[dict]] = {}
    for r in rows:
        name = (r.get("Kernel Name") or r.get("Demangled Name") or "?").split("(")[0]
        by_kernel.setdefault(name, []).append(r)

    out: dict[str, dict[str, float]] = {}
    for name, rs in by_kernel.items():
        vals: dict[str, float] = {}
        for metric, (label, _unit) in WANTED.items():
            got = []
            for r in rs:
                raw = r.get(metric)
                if raw in (None, "", "n/a"):
                    continue
                try:
                    got.append(float(str(raw).replace(",", "")))
                except ValueError:
                    continue
            if got:
                vals[label] = sum(got) / len(got)
        if vals:
            out[name] = vals
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("ncu_dir", nargs="?", default="results/ncu")
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    ncu = find_ncu()
    reps = sorted(pathlib.Path(args.ncu_dir).glob("*.ncu-rep"))
    if not reps:
        raise SystemExit(f"no .ncu-rep files in {args.ncu_dir}; run profiling/run_ncu.ps1 first")

    labels = [lbl for lbl, _ in WANTED.values()]
    lines = [
        "# Nsight Compute summary",
        "",
        "Averaged over the profiled launches of each kernel. "
        "`sectors/req` is sectors per global load request. These kernels load "
        "128 bits per lane, so a warp covers 32 x 16 B = 512 B = **16** sectors: "
        "16 is perfect coalescing here, and 32 would mean every lane fetched its "
        "own sector.",
        "",
        "| config | kernel | " + " | ".join(labels) + " |",
        "|---|---|" + "---:|" * len(labels),
    ]
    for rep in reps:
        rows = read_report(ncu, rep)
        if not rows:
            lines.append(f"| {rep.stem} | *(no data — counter permissions?)* |"
                         + " |".join([""] * (len(labels) + 1)))
            continue
        for kernel, vals in summarize(rows).items():
            cells = []
            for lbl in labels:
                v = vals.get(lbl)
                cells.append("--" if v is None else (f"{v:,.0f}" if abs(v) >= 100
                                                     else f"{v:.2f}"))
            lines.append(f"| {rep.stem} | `{kernel[:44]}` | " + " | ".join(cells) + " |")

    text = "\n".join(lines) + "\n"
    if args.out:
        pathlib.Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        pathlib.Path(args.out).write_text(text, encoding="utf-8")
        print(f"wrote {args.out}")
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
